import OpenAI from 'openai';
import dotenv from 'dotenv';

dotenv.config();

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

// Topics extracted from Ginny's language palette, thematic anchors, and newsletters
const TOPICS = [
  // Consciousness & Self-awareness
  'awake',
  'inner work',
  'presence',
  'frequency',
  'truth',
  'awareness',
  'stillness',
  'consciousness',
  'self-awareness',
  'inner compass',
  'trusting your gut',
  
  // Leadership & Agency
  'leadership',
  'power',
  'purpose',
  'practice',
  'boundaries',
  'responsibility',
  'courage',
  'discipline',
  'agency',
  'decisiveness',
  'speaking up',
  'holistic leadership',
  'crisis leadership',
  
  // Human Connection
  'love',
  'empathy',
  'trust',
  'compassion',
  'wholeness',
  'connection',
  'building trust',
  'reading the room',
  
  // Transformation & Growth
  'remembering',
  'refinement',
  'alignment',
  'evolution',
  'becoming',
  'transformation',
  'leveling up',
  'pushing limits',
  'taking risks',
  
  // Thematic Anchors - Know Yourself
  'self-honesty',
  'self-trust',
  'competencies',
  'inherited beliefs',
  'self-imposed limits',
  
  // Thematic Anchors - Speak Your Truth
  'authentic voice',
  'integrity',
  'difficult conversations',
  'professional disrespect',
  
  // Thematic Anchors - Inspire Love
  'leading with empathy',
  'protecting well-being',
  'safety first',
  
  // Thematic Anchors - Expand Consciousness
  'curiosity',
  'perspective',
  'humility',
  'global mindset',
  'discernment',
  'adaptability',
  'cross-disciplinary thinking',
  
  // Thematic Anchors - Activate Mastery
  'mastery',
  'accountability',
  'intention setting',
  'goals that scare you',
  
  // Concepts from newsletters
  'waking up',
  'fitting in',
  'honesty with feelings',
  'self-respect',
  'impact',
  'urgency vs. stillness',
  'meeting yourself',
  'performance vs. presence',
  'leading from alignment',
  'approval-seeking',
  'team leadership',
  'inner calm',
  'seeing the whole picture',
  'root causes',
  'surface-level solutions',
  'organizational distress',
  'how work flows',
  'recurring challenges',
  'structural problems',
  'uncertainty',
  'confidence',
  'resourcefulness',
  'network',
  'catastrophizing',
  'taking action',
  'decision paralysis',
  'selective adaptation',
  'information overload',
  'retaining wisdom',
  'deep engagement',
  'comfort zone',
  'self-doubt',
  'rationalizations',
  'resilience',
  'worthiness',
  'courage vs. talent',
  'broken promises',
  'dignity',
  'boundaries in action',
  'saying no',
  'resisting change',
  'personal agency',
  'freedom to respond',
  'self-care as leadership',
  
  // Topics from videos/podcasts
  'it\'s not always about you',
  'dream job',
  'holding on to nothing',
  'conscious capitalism',
  'overachiever pitfalls',
  'spotting manipulation',
  'rewire, reframe, reimagine',
  'the art of letting go',
  'tell people what you want',
  'wasted motion',
  'workplace swirl',
  'rearview mirror vs windshield',
  'where is your focus',
  'leading with fear',
  'afraid to lead',
  'owning your story',
  'why people quit',
  'passive-aggressive behavior',
  'email management',
  'inbox control',
  'office politics',
  'playing the game',
  'manager vs leader',
  'workplace incivility',
  'standing up for yourself',
  'rising above',
  'workplace bully',
  'fighting back professionally',
  'toxic workplace',
  'protecting yourself',
  'fire drills',
  'managing workplace relationships',
  'first 100 days',
  'negotiating an offer',
  'when to walk away',
  'people you need in your network',
  'free agency',
  'power player of your career',
  'how to pivot',
  'getting what you deserve',
  'empathy in action',
  'love in leadership',
  'knowledge vs information',
  'busting the good girl myth',
  'leadership brand',
  'shifting the power',
  'the 5/95 solution',
  'rejection',
  'what rejection means',
  'leveling up your job search',
  'enabling bad behavior',
  'micromanaging',
  'release your grip',
  'giving feedback',
  'receiving feedback',
  'loyalty is not a strategy',
  'using your voice in the workplace',
  'managing expectations',
  'career map',
  'navigating your career',
  'habits of a conscious leader',
  'ego sabotaging success',
  'reading your own energy',
  'reading others\' energy',
  'blind ambition',
  'reconnect to your true self',
  'five dimensions of conscious leadership',
  'favoritism',
  'nepotism',
  'legacy employees',
  'create what you want',
  'stop resisting what is',
  'excellence',
  'setting the standard',
  'saying no and meaning it',
  'performance reviews',
  'high achiever with challenging personality',
  'healing the divine masculine',
  'the art of interviewing',
  'fending off mediocrity',
  'inspiring excellence',
  'be an activist for unity',
  'unity consciousness',
  'staying in your lane',
  'leaving your job the right way',
  'overcoming insecurities as a leader',
  'autonomy and protocol',
  'optimizing work through meaning',
  'optimizing work through curiosity',
  'rethinking your job search',
  'feeling trapped',
  'managing insecurity',
  'are you playing the game or getting played',
  'becoming your own compass',
  'is professionalism dead',
  'victim vs activist',
  'step into your greatness',
  'stop playing small',
  'pattern matching',
  'navigating power with integrity',
  'mental health',
  'lead without overcomplicating',
  'power of femininity at work',
  'passed over for promotion',
  'the art of problem solving',
  'breaking into the C-Suite',
  'imposter syndrome',
  'mentorship alternatives',
  'power of the pause',
  'finding your voice',
  'emotional intelligence',
  'competencies vs pedigree',
  'words to eliminate',
  'retaining talent',
  'leading unmotivated teams',
  'aligning career to values',
  'setting boundaries at work',
  'get noticed at work',
  'get the promotion',
  'diversity as a leadership problem',
];

/**
 * Randomly selects an item from an array
 */
function getRandomItem(array) {
  return array[Math.floor(Math.random() * array.length)];
}

export async function generateOracleCard() {
  // Randomly select a topic
  const topic = getRandomItem(TOPICS);
  
  // Generate the input prompt with just the topic
  const input = `generate about ${topic}`;
  
  console.log(`🎲 Randomly selected topic: "${topic}"`);
  console.log(`📝 AI input: "${input}"`);
  
  const res = await openai.responses.create({
    prompt: {
      id: process.env.OPENAI_PROMPT_ID,
      version: process.env.OPENAI_PROMPT_VERSION,
    },
    input: input,
  });
  return res.output_text.trim();
}

